#!/bin/bash
PHOTOSPREFIX=.
TARGET=${PHOTOSPREFIX}/videos/days

cd ${PHOTOSPREFIX}/stills
for DAY in 201[5-6][0-1][0-9][0-3][0-9]
do
  TARGETFILE=${TARGET}/${DAY}.mp4
  echo "Checking ${TARGETFILE}"
  if [ ! -e ${TARGETFILE} ]; then
	  ${PHOTOSPREFIX}/scripts/makedayvideo ${DAY}
	else
	  echo "${DAY} exists"
	fi
done

