#!/bin/bash
PHOTOSPREFIX=.
cd ${PHOTOSPREFIX}/stills
for DAY in 201[5-6][0-1][0-9][0-3][0-9]
do
  echo "Checking ${PHOTOSPREFIX}/mean/${DAY}-mean.jpg"
  if [ ! -e ${PHOTOSPREFIX}/mean/${DAY}-mean.jpg ]; then
	  ${PHOTOSPREFIX}/scripts/makemean ${DAY}
	else
	  echo "${DAY} exists"
	fi
done

