#!/bin/bash
TZ='America/Los_Angeles'; export TZ
YESTERDAY=$(date +"%Y%m%d" --date=yesterday)
TODAY=$(date +"%Y%m%d")
date
echo $TODAY

echo "Syncing..."
rsync -axv pi@zerow.local:/var/www/html/lapse/ /mnt/media/Projects/lapse-2020/stills/

echo "Making medium..."
scripts/makemedium ${TODAY}

date
