#!/bin/bash
TZ='America/Los_Angeles'; export TZ
DAY=$1
PHOTOSPREFIX=.
echo "Making mean ${DAY} from images every hour"
convert -evaluate-sequence mean ${PHOTOSPREFIX}/stills/${DAY}/$DAY??000?.jpg ${PHOTOSPREFIX}/mean/${DAY}-mean.jpg
