#!/bin/bash
TZ='America/Los_Angeles'; export TZ
DAY=$1
PHOTOSPREFIX=.
echo "Making mean ${DAY} from images every half hour"
convert -evaluate-sequence mean ${PHOTOSPREFIX}/stills/${DAY}/$DAY*[03]00[0-9].jpg ${PHOTOSPREFIX}/mean/${DAY}-mean.jpg
