#!/bin/bash
TZ='America/Los_Angeles'; export TZ
YESTERDAY=$(date +"%Y%m%d" --date=yesterday)
TODAY=$(date +"%Y%m%d")
date
echo $TODAY

echo "Syncing..."
rsync -axvv ${1}:sutro/stills/ stills/

echo "Making medium..."
scripts/makemedium ${TODAY}

date
