#!/bin/bash
TZ='America/Los_Angeles'; export TZ
YESTERDAY=$(date +"%Y%m%d" --date=yesterday)
TODAY=$(date +"%Y%m%d")
date
echo $TODAY

echo "Syncing..."
rsync -axv  ${1}:sutro/stills/ stills/

echo "Linking..."
rm latest.jpg
ln -s stills/${TODAY}/`ls stills/${TODAY} | tail -n 1` latest.jpg

echo "Making medium..."
scripts/makemedium ${TODAY}

echo "Making small images..."
scripts/makesmall ${TODAY}

echo "Making day grid..."
scripts/makedaygrid ${TODAY}
ln -f -s daygrid/${TODAY}-grid.jpg today-grid.jpg
date
