#!/bin/bash
LAPSEPREFIX=.
STILLSPREFIX=${LAPSEPREFIX}/stills
SMALLPREFIX=${LAPSEPREFIX}/medium

if [ $# -eq 1 ]; then
  DAY=$1
else
  DAY=20*
fi

for daypath in ${STILLSPREFIX}/${DAY}
do
  day=${daypath##*/}
  smalldaypath=${SMALLPREFIX}/${day}
  mkdir -p ${smalldaypath}
  for image in ${daypath}/*.jpg
  do
    imageroot=${image##*/}
    small=${smalldaypath}/${imageroot%.*}.jpg
    if [ ! -e ${small} ]; then
      echo "convert -resize 50% -quality 90 ${image} ${small}"
      convert -resize 50% -quality 90 ${image} ${small}
#    else
#     echo "${small} exists"
    fi
  done
done
