#!/bin/bash
LAPSEPREFIX=.
SIZE=160x90
STILLSPREFIX=${LAPSEPREFIX}/stills
SMALLPREFIX=${LAPSEPREFIX}/${SIZE}

if [ $# -eq 1 ]; then
  DAY=$1
else
  DAY=20*
fi

for daypath in ${STILLSPREFIX}/${DAY}
do
  day=${daypath##*/}
  smalldaypath=${SMALLPREFIX}/${day}
  mkdir -p ${smalldaypath}
  for image in ${daypath}/*.jpg
  do
    imageroot=${image##*/}
    small=${smalldaypath}/${imageroot%.*}.png
    if [ ! -e ${small} ]; then
#      echo "convert -resize ${SIZE} -depth 24 ${image} ${small}"
      convert -resize ${SIZE} -depth 24 ${image} ${small}
#    else
#     echo "${small} exists"
    fi
  done
done
