#!/bin/bash
DIMENSION=$1
LAPSEPREFIX=.
STILLSPREFIX=${LAPSEPREFIX}/stills
SMALLPREFIX=${LAPSEPREFIX}/${DIMENSION}

if [ $# -eq 2 ]; then
  DAY=$2
else
  DAY=20*
fi

for daypath in ${STILLSPREFIX}/${DAY}
do
  day=${daypath##*/}
  smalldaypath=${SMALLPREFIX}/${day}
  echo "Making ${smalldaypath}"
  mkdir -p ${smalldaypath}
  for image in ${daypath}/*.jpg
  do
    imageroot=${image##*/}
    small=${smalldaypath}/${imageroot%.*}.jpg
    if [ ! -e ${small} ]; then
      echo "converting ${image} to ${small}"
      convert -crop '1800x1080+0+0' -resize ${DIMENSION} -gravity center ${image} ${small}
#    else
#     echo "${small} exists"
    fi
  done
done
