#!/bin/bash
TZ='America/Los_Angeles'; export TZ
DAY=$1
#SIZE=160x90
SIZE=320x180

if [ $# -eq 1 ]; then
  DAY=$1
else
  DAY=20*
fi

for daypath in ${DAY}
do
  GRIDFILE=daygrid/${daypath}-grid.jpg
  if [ $DAY -eq $1 ]; then
  	 rm ${GRIDFILE}
  	 echo "Removed existing ${GRIDFILE}"
  fi
  
  if [ -e ${GRIDFILE} ]; then
      echo "Skipping day grid ${GRIDFILE}, it already exists"
  else
     echo "Making day grid ${GRIDFILE}"
     montage ${SIZE}/${daypath}/*00?.png -background black -geometry ${SIZE} -tile 12x12 ${GRIDFILE}
  fi
done
